### ISSUE TITLE
Change from vorpal framework to oclif

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-commander#524]
### Description

Vorpal is not actively developed, and most of the dependencies used are very old.
Rather than maintaining our fork version of vorpal,
it would be better for development and maintenance to move to the actively developed framework.

### Tasks
- [x] Change the library and change setup #554
- [x] Update the utils to match the framework and update the test #555
- [x] Migrate command config #556
- [x] Migrate command account #557
- [x] Migrate command transaction #558
- [x] Migrate command message #559
- [x] Migrate command delegate #560
- [x] Migrate command passphrase #561
- [x] Migrate command node #562
- [x] Migrate command block #563 
- [x] Migrate command signature #571

**Comment by willclarktech** [comment]
This sounds great, but:
1. It only seems to support Node.js v8+, so we'll need to coordinate with other products.
2. It would be nice to know if there are any other alternatives?
