### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-commander#649]
### Description
Main framework Oclif supports and focus on TypeScript, and lisk-elements is moving to TypeScript now.

Lisk-commander also should be using TypeScript, too.

- [x] Create basic settings for TypeScript #652
- [x] Open Convert Util file into TypeScript #653
- [x] Open Convert account command to TypeScript #654
- [x] Open Convert block command to TypeScript #655
- [x] Open Convert config command to TypeScript #656
- [x] Open Convert delegate command to TypeScript #657
- [x] Open Convert message command to TypeScript #658
- [x] Convert node command to TypeScript #659
- [x] Convert passphrase command to TypeScript #660
- [x] Open Convert signature command to TypeScript #661
- [x] Convert transaction command to TypeScript #662
- [x] Convert copyright and warranty command to TypeScript #682 

### Additional Information

Lisk-Elements need to support TypeScript first
